export const ROUTES = [
    { name: 'Tic-Tac-Toe', path: '/tic-tac-toe', description: "A classic two-player strategy game where Xs and Os compete to align three in a row.", github: "https://github.com/sushma-priyadharssini/react-ui-coding/blob/main/src/libs/tic-tac-toe/board.jsx" },
    { name: 'Progress Bar', path: '/progress-bar', description: "A visual indicator that displays the completion status of a task or process in real time.", github: "https://github.com/sushma-priyadharssini/react-ui-coding/blob/main/src/libs/progress-bar/progress-bar.js" },
    { name: 'Analog Clock', path: '/analog-clock', description: "A real-time clock interface that displays the current time with moving hour, minute, and second hands.", github: "https://github.com/sushma-priyadharssini/react-ui-coding/blob/main/src/libs/analog-clock/clock.js" },
    { name: 'Digital Clock', path: '/digital-clock', description: "A real-time clock interface that displays the current time in a numeric digital format.", github: "https://github.com/sushma-priyadharssini/react-ui-coding/blob/main/src/libs/digital-clock/clock.js" },
    { name: 'Dice Roller', path: '/dice-roller', description: "A simple game that simulates rolling dice to generate random outcomes.", github: "https://github.com/sushma-priyadharssini/react-ui-coding/blob/main/src/libs/dice-roller/dice.js" },
    { name: 'To Do List', path: '/to-do-list', description: "A task management interface that lets users add, remove, and track their daily to-dos.", github: "https://github.com/sushma-priyadharssini/react-ui-coding/blob/main/src/libs/to-do-list/to-do-list.js" },
    { name: 'Modal Dialog', path: '/modal-dialog', description: "A pop-up interface element that captures user attention for important messages or actions without leaving the current page.", github: "https://github.com/sushma-priyadharssini/react-ui-coding/blob/main/src/libs/modal-dialog/modal.js" },
    { name: 'Star Rating', path: '/star-rating', description: "An interactive component that lets users rate items or experiences by selecting a number of stars.", github: "https://github.com/sushma-priyadharssini/react-ui-coding/blob/main/src/libs/star-rating/star-rating.js" },
    { name: 'Grid Lights', path: '/grid-lights', description: "Grid of lights where the lights deactivate in the reverse order they were activated", github: "https://github.com/sushma-priyadharssini/react-ui-coding/blob/main/src/libs/grid-lights/grid-lights.js" },
    { name: 'Like Button', path: '/like-button', description: "A clickable button that allows users to express appreciation with a single tap.", github: "https://github.com/sushma-priyadharssini/react-ui-coding/blob/main/src/libs/like-button/like-button.js" },
    { name: 'Accordion', path: '/accordion', description: "A collapsible UI component that expands to reveal hidden content and contracts to save space.", github: "https://github.com/sushma-priyadharssini/react-ui-coding/blob/main/src/libs/accordion/accordion.js" },
]